export const LEGEND_LINES = [
  "THE SKIN REMEMBERS WHAT THE MIND FORGETS",
  "EVERY LINE IS A DECISION YOU CANNOT TAKE BACK",
  "WE WRITE THE STORIES PEOPLE CARRY FOREVER",
  "INK IS THE ONLY HONEST BIOGRAPHY",
  "THE MARK IS ALREADY WAITING",
  "PERMANENCE IS THE POINT",
] as const;
