export const LEGEND_LINES = [
  "THE MARK STAYS. EVERYTHING ELSE FADES",
  "SKIN IS THE ONLY ARCHIVE THAT DOESN'T LIE",
  "WE DON'T DECORATE. WE COMMIT",
  "LATE NIGHTS. PERMANENT DECISIONS",
  "THE NEEDLE DOESN'T NEGOTIATE",
  "WHAT YOU CARRY IS WHAT YOU CHOSE",
] as const;
